platform :ios, '14.0'

# Disable CocoaPods analytics
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  '/Users/apple/Documents/sdk/flutter'
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
#  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

  # Uncomment only the pod you are using, and comment the other one
  # pod 'Reachability', :inhibit_warnings => true # Comment this if using ReachabilitySwift
  #pod 'ReachabilitySwift', '~> 5.2.3' # Keep this if you're using ReachabilitySwift
  pod 'Firebase/Analytics'
  pod 'ReachabilitySwift'

  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
